import { useEffect, useState } from 'react';
import { Alert, Switch, Text, View } from 'react-native';
import { useSession } from '@/state/session';
import { messageFor } from '@/lib/server';
import { RoomButton, RoomInput, ui } from './RoomUi';
const kinds = ['webdav', 'ftp', 'openlist', 'emby', 'jellyfin'];
type Mount = { id: number; name: string; serverUrl: string; path?: string; port?: number; username?: string; directLink?: boolean; type: string };
const empty = { name: '', serverUrl: '', path: '/', port: '', username: '', password: '', apiKey: '', directLink: false };
export function MountManager() {
  const { request, session } = useSession(); const [kind, setKind] = useState('webdav'); const [mounts, setMounts] = useState<Mount[]>([]); const [edit, setEdit] = useState<number | null>(null);
  const [fields, setFields] = useState(empty); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [open, setOpen] = useState(false);
  useEffect(() => { if (!open) return; let active = true; void request<{ mounts: Mount[] }>(`/api/${kind}/mounts`).then(value => { if (active) setMounts(value.mounts); }).catch(failure => { if (active) setMessage(messageFor(failure)); }); return () => { active = false; }; }, [kind, request, open]);
  const task = async (work: () => Promise<void>) => { setBusy(true); setMessage(''); try { await work(); } catch (failure) { setMessage(messageFor(failure)); } finally { setBusy(false); } };
  const body = () => ({ ...fields, ...(fields.port ? { port: Number(fields.port) } : {}), ...(!fields.password && edit ? { password: undefined } : {}), ...(!fields.apiKey && edit ? { apiKey: undefined } : {}) });
  const load = async () => setMounts((await request<{ mounts: Mount[] }>(`/api/${kind}/mounts`)).mounts);
  const reset = () => { setEdit(null); setFields(empty); };
  return <View style={ui.card}><RoomButton label={open ? '收起媒体账号管理' : '媒体账号与挂载管理'} secondary onPress={() => { setOpen(value => !value); reset(); }} />{open ? <><Text style={ui.muted}>仅管理当前账号的来源。SMB 请在服务器挂载后从服务器文件选择；v4.2.0 没有独立 SMB 挂载接口。</Text><View style={ui.row}>{kinds.map(value => <RoomButton key={value} label={value} secondary disabled={busy || value === kind} onPress={() => { setKind(value); reset(); setMessage(''); }} />)}</View>{mounts.map(item => <View key={item.id} style={ui.card}><Text style={ui.text}>{item.name}</Text><View style={ui.row}><RoomButton label="编辑挂载" secondary disabled={busy} onPress={() => { setEdit(item.id); setFields({ ...empty, ...item, port: item.port ? String(item.port) : '', username: item.username || '', path: item.path || '/', directLink: !!item.directLink }); }} /><RoomButton label="删除挂载" secondary disabled={busy} onPress={() => Alert.alert('删除挂载', `删除 ${item.name}？`, [{ text: '取消' }, { text: '删除', style: 'destructive', onPress: () => void task(async () => { await request(`/api/${kind}/mounts/${item.id}`, { method: 'DELETE' }); reset(); await load(); }) }])} /></View></View>)}<Text style={ui.title}>{edit ? '编辑来源' : '新增来源'}</Text>{(['name', 'serverUrl', 'username', 'password', ...(kind === 'emby' || kind === 'jellyfin' ? ['apiKey'] : ['path']), ...(kind === 'ftp' ? ['port'] : [])] as (keyof typeof empty)[]).filter(key => key !== 'directLink').map(key => <RoomInput key={key} value={String(fields[key])} onChangeText={value => setFields(old => ({ ...old, [key]: value }))} secureTextEntry={key === 'password' || key === 'apiKey'} autoCapitalize="none" placeholder={({ name: '来源名称', serverUrl: '服务器地址', username: '用户名', password: edit ? '新密码（留空保留）' : '密码', apiKey: edit ? '新 API Key（留空保留）' : 'API Key（或用户名密码）', path: '根路径', port: '端口', directLink: '' })[key]} />)}{kind !== 'ftp' ? <View style={ui.row}><Text style={ui.text}>直接连接媒体源</Text><Switch value={fields.directLink} onValueChange={value => setFields(old => ({ ...old, directLink: value }))} /></View> : null}<View style={ui.row}><RoomButton label="测试连接" secondary disabled={busy || !fields.serverUrl.trim()} onPress={() => void task(async () => { const result = await request<{ message?: string }>(`/api/${kind}/mounts/test`, { method: 'POST', body: JSON.stringify(body()) }); setMessage(result.message || '连接测试成功'); })} /><RoomButton label="保存挂载" disabled={busy || !fields.name.trim() || !fields.serverUrl.trim() || session?.user.role === 'guest'} onPress={() => void task(async () => { const result = await request<{ warning?: string }>(`/api/${kind}/mounts${edit ? `/${edit}` : ''}`, { method: edit ? 'PUT' : 'POST', body: JSON.stringify(body()) }); reset(); await load(); setMessage(result.warning || '已保存'); })} /><RoomButton label="清空表单" secondary disabled={busy} onPress={reset} /></View>{message ? <Text style={ui.muted}>{message}</Text> : null}</> : null}</View>;
}
