import { useState } from 'react';
import { Text, View } from 'react-native';
import { useSession } from '@/state/session';
import { resolveLocalBili } from '@/lib/biliNative';
import { messageFor } from '@/lib/server';
import { BiliCatalog } from './BiliCatalog';
import { BiliAccount } from './BiliAccount';
import { RoomButton, RoomInput, ui } from './RoomUi';
export type Song = { songId: number; name: string; artist: string; album: string; cover: string; durationMs: number; vip: boolean; biliBvid?: string; biliCid?: number };
type NcmSong = { id: number; name: string; ar?: { name: string }[]; artists?: { name: string }[]; al?: { name: string; picUrl: string }; album?: { name: string; picUrl: string }; dt?: number; duration?: number; fee?: number };
const song = (item: NcmSong): Song => ({ songId: item.id, name: item.name, artist: (item.ar || item.artists || []).map(value => value.name).join(' / '), album: (item.al || item.album)?.name || '', cover: (item.al || item.album)?.picUrl || '', durationMs: item.dt || item.duration || 0, vip: item.fee === 1 });
export function MusicLibrary({ showSongs, add }: { showSongs: (songs: Song[]) => void; add: (song: Song) => Promise<void> }) {
  const { request, requestText } = useSession(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [name, setName] = useState(''); const [playlists, setPlaylists] = useState<{ id: number; name: string; trackCount: number }[]>([]);
  const ncm = async <T,>(path: string): Promise<T> => { const result = JSON.parse(await requestText(`/api/music/ncm${path}`)); if (result.code !== 200) throw new Error(result.message || '网易云请求失败'); return result; };
  const task = async (work: () => Promise<void>) => { setBusy(true); setMessage(''); try { await work(); } catch (failure) { setMessage(messageFor(failure)); } finally { setBusy(false); } };
  return <View style={ui.card}><Text style={ui.title}>我的网易云音乐</Text><View style={ui.row}><RoomButton label="刷新网易云账号" secondary disabled={busy} onPress={() => void task(async () => { const value = await request<{ loggedIn: boolean; nickname?: string; vipStatus?: number }>('/api/music/login/status'); setMessage(value.loggedIn ? `${value.nickname || '已登录'}${value.vipStatus === 1 ? ' · VIP' : ''}` : '未登录网易云'); })} /><RoomButton label="退出网易云账号" secondary disabled={busy} onPress={() => void task(async () => { await request('/api/music/logout', { method: 'POST', body: '{}' }); setPlaylists([]); setMessage('已退出网易云账号'); })} /><RoomButton label="我的歌单" secondary disabled={busy} onPress={() => void task(async () => { const account = await ncm<{ profile: { userId: number } }>('/user/account'); if (!account.profile?.userId) throw new Error('请先扫码登录网易云账号'); const result = await ncm<{ playlist: typeof playlists }>(`/user/playlist?uid=${account.profile.userId}&limit=100`); setPlaylists(result.playlist); })} /><RoomButton label="每日推荐歌曲" secondary disabled={busy} onPress={() => void task(async () => { const value = await ncm<{ data: { dailySongs: NcmSong[] } }>('/recommend/songs'); showSongs(value.data.dailySongs.map(song)); })} /></View>{playlists.map(item => <RoomButton key={item.id} label={`${item.name} · ${item.trackCount} 首`} secondary disabled={busy} onPress={() => void task(async () => { const result = await ncm<{ songs: NcmSong[] }>(`/playlist/track/all?id=${item.id}&limit=500`); showSongs(result.songs.map(song)); })} />)}<RoomInput value={name} onChangeText={setName} placeholder="新建网易云歌单名称" /><RoomButton label="创建网易云歌单" secondary disabled={busy || !name.trim()} onPress={() => void task(async () => { await ncm(`/playlist/create?${new URLSearchParams({ name: name.trim(), type: 'NORMAL' })}`); setName(''); setMessage('歌单已创建，请刷新我的歌单'); })} />{message ? <Text style={ui.muted}>{message}</Text> : null}<BiliAccount /><BiliCatalog choose={item => void task(async () => { const media = await resolveLocalBili(`https://www.bilibili.com/video/${item.bvid}${item.cid ? `?cid=${item.cid}` : ''}`); const part = media.pages?.find(value => value.page === media.currentPage) || media.pages?.[0]; if (!part?.cid) throw new Error('没有可用的 B站音频分 P'); await add({ songId: 0, name: item.title, artist: item.author || 'B站', album: '', cover: '', durationMs: (media.duration || 0) * 1000, vip: false, biliBvid: item.bvid, biliCid: part.cid }); })} /></View>;
}
