import { useEffect, useState } from 'react';
import { Modal, ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useSession } from '@/state/session';
import { useAppearance } from '@/state/appearance';
import { RoomButton, RoomInput, ui as baseUi } from './RoomUi';
import { MediaImage } from './MediaImage';
type Comment = { commentId: number; content: string; user?: { nickname?: string; avatarUrl?: string }; timeStr?: string };
export function SongComments({ songId, close }: { songId: number | null; close: () => void }) {
  const theme = useAppearance(); const ui = theme.styles(baseUi); const { requestText } = useSession(); const [items, setItems] = useState<Comment[]>([]); const [parent, setParent] = useState<number | null>(null); const [draft, setDraft] = useState(''); const [message, setMessage] = useState(''); const [version, setVersion] = useState(0); const [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; void Promise.resolve().then(() => { if (active) { setParent(null); setDraft(''); } }); return () => { active = false; }; }, [songId]);
  useEffect(() => { if (!songId) return; const cancel = new AbortController(); void Promise.resolve().then(() => { if (!cancel.signal.aborted) setItems([]); }); const path = parent ? `/comment/floor?parentCommentId=${parent}&id=${songId}&type=0&limit=30` : `/comment/music?id=${songId}&limit=30`; void requestText(`/api/music/ncm${path}`, { signal: cancel.signal }).then(raw => { if (cancel.signal.aborted) return; const value = JSON.parse(raw); if (value.code !== 200) throw new Error(); setItems(value.data?.comments || value.comments || []); setMessage(''); }).catch(() => { if (!cancel.signal.aborted) setMessage('评论获取失败，可刷新重试'); }); return () => cancel.abort(); }, [songId, parent, requestText, version]);
  return <Modal visible={!!songId} presentationStyle="fullScreen" animationType={theme.preferences.reduceMotion ? 'none' : 'slide'} supportedOrientations={['portrait', 'landscape']} onRequestClose={close}><SafeAreaView style={{ flex: 1, padding: 16, backgroundColor: theme.dark ? '#111417' : '#f1f5f3' }}><View style={ui.row}><Text style={[ui.title, { flex: 1 }]}>{parent ? '楼层回复' : '歌曲评论'}</Text><RoomButton label="关闭" secondary onPress={close} /></View><View style={ui.row}>{parent ? <RoomButton label="返回评论" secondary onPress={() => setParent(null)} /> : null}<RoomButton label="刷新" secondary onPress={() => setVersion(old => old + 1)} /></View><ScrollView contentContainerStyle={ui.content} keyboardShouldPersistTaps="handled">{items.map(item => <View key={item.commentId} style={ui.card}><View style={ui.row}><MediaImage source={{ uri: item.user?.avatarUrl || '' }} style={{ width: 44, height: 44, borderRadius: 22 }} /><Text style={ui.text}>{item.user?.nickname || '用户'}</Text></View><Text style={ui.text}>{item.content}</Text><Text style={ui.muted}>{item.timeStr}</Text>{!parent ? <RoomButton label="查看 / 回复楼层" secondary onPress={() => setParent(item.commentId)} /> : null}</View>)}{message ? <Text style={ui.error}>{message}</Text> : null}</ScrollView><RoomInput value={draft} onChangeText={setDraft} placeholder={parent ? '回复当前楼层' : '发表歌曲评论'} multiline /><RoomButton label={busy ? '发送中…' : '发送评论'} disabled={!draft.trim() || busy} onPress={() => { setBusy(true); const params = new URLSearchParams({ t: parent ? '2' : '1', type: '0', id: String(songId), content: draft.trim(), ...(parent ? { commentId: String(parent) } : {}) }); void requestText(`/api/music/ncm/comment?${params}`).then(raw => { const value = JSON.parse(raw); if (value.code !== 200) throw new Error(); setDraft(''); setVersion(old => old + 1); }).catch(() => setMessage('发表评论失败，请确认网易云登录状态与账号权限')).finally(() => setBusy(false)); }} /></SafeAreaView></Modal>;
}
